/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rgf_pck_alumno;

import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author dary_
 */
public class rgf_form extends javax.swing.JFrame {

    /**
     * Creates new form rgf_form
     */
    ArrayList<Alumno> alumnos = new ArrayList<>();
    ValidarDatos validar;
    public rgf_form() {
        initComponents();
        validar = new ValidarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optGenero = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNumControl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAperllidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        optFemenino = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        optMasculino = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cboCarreras = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Datos del Alumno:");

        jLabel2.setText("Núm. De control: ");

        jLabel3.setText("Nombre(s): ");

        jLabel4.setText("Apellido Paterno:");

        jLabel5.setText("Apellido Materno: ");

        optFemenino.setText("Femenino");

        jLabel6.setText("Genero: ");

        optMasculino.setText("Masculino");
        optMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMasculinoActionPerformed(evt);
            }
        });

        jLabel7.setText("Carrera: ");

        cboCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería Civil", "Ingeniería en Gestión Empresarial", "Ingeniería Electrónica", "Ingeniería Eléctrica", "Ingeniería en Sistemas Computacionales", "Ingeniería Industrial", "Ingeniería Mecánica", "Ingeniería Química", "Licenciatura en Administración" }));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNumControl)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAperllidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(cboCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optFemenino)
                                .addGap(18, 18, 18)
                                .addComponent(optMasculino))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnMostrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAperllidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optFemenino)
                    .addComponent(optMasculino)
                    .addComponent(btnAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optMasculinoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        int numControl;
        String nombre;
        String apellidoPaterno;
        String apellidoMaterno;
        char genero = '\0';
        String carrera = null;
        optGenero.add(optFemenino);
        optGenero.add(optMasculino);
        
        if (!optFemenino.isSelected() && !optMasculino.isSelected()) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un género.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }
    
    do {
        numControl = Integer.parseInt(txtNumControl.getText());
        if (!validar.validarNumControl(numControl)) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un numero de control válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } while (!validar.validarNumControl(numControl));
    
    do {
        nombre = txtNombre.getText();
        if (!validar.validarNombreApellido(nombre)) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } while (!validar.validarNombreApellido(nombre));
    
 
    do {
        apellidoPaterno = txtAperllidoPaterno.getText();
        if (!validar.validarNombreApellido(apellidoPaterno)) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un apellido paterno válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
    } while (!validar.validarNombreApellido(apellidoPaterno));
    
    
    do {
        apellidoMaterno = txtApellidoMaterno.getText();
        if (!validar.validarNombreApellido(apellidoMaterno)) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un apellido materno válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
    } while (!validar.validarNombreApellido(apellidoMaterno));
    
    if (optFemenino.isSelected()) {
        genero = 'F';
    } else if (optMasculino.isSelected()) {
        genero = 'M';
    }
    carrera = cboCarreras.getSelectedItem().toString();
    Alumno alumno = new Alumno(numControl, nombre, apellidoPaterno, apellidoMaterno,genero,carrera);
    alumnos.add(alumno);
    txtNumControl.setText("");
    txtNombre.setText("");
    txtAperllidoPaterno.setText("");
    txtApellidoMaterno.setText("");

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtNumControl.setText("");
        txtNombre.setText("");
        txtAperllidoPaterno.setText("");
        txtApellidoMaterno.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        if (alumnos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay alumnos registrados.", "Información", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // Construir el mensaje con los detalles de todos los alumnos
    StringBuilder mensaje = new StringBuilder("Lista de Alumnos:\n");
    for (Alumno alumno : alumnos) {
        mensaje.append("\nNúmero de control: ").append(alumno.getNumControl())
               .append("\nNombre: ").append(alumno.getNombre())
               .append("\nApellido paterno: ").append(alumno.getApellidoPaterno())
               .append("\nApellido materno: ").append(alumno.getApellidoMaterno())
               .append("\nGénero: ").append(alumno.getGenero())
               .append("\nCarrera: ").append(alumno.getCarrera())
               .append("\n--------------------------\n");
    }
    
    // Mostrar el mensaje con los detalles de todos los alumnos
    JOptionPane.showMessageDialog(this, mensaje.toString(), "Alumnos Registrados", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rgf_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rgf_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rgf_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rgf_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rgf_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> cboCarreras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton optFemenino;
    private javax.swing.ButtonGroup optGenero;
    private javax.swing.JRadioButton optMasculino;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtAperllidoPaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumControl;
    // End of variables declaration//GEN-END:variables
}
